# Generated by Django 2.0.4 on 2018-07-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LlikeCount',
            new_name='LikeCount',
        ),
    ]
