# Generated by Django 2.0.4 on 2018-05-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180509_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readnum',
            old_name='read_num',
            new_name='get_read_num',
        ),
    ]
