# Generated by Django 2.0.4 on 2018-11-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181119_1836'),
        ('blog', '0010_auto_20180515_0843'),
    ]

    operations = [
    ]
