# Generated by Django 2.0.4 on 2018-07-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20180702_1951'),
        ('comment', '0004_auto_20180704_1512'),
    ]

    operations = [
    ]
